/** @type {import('tailwindcss').Config} */
export default {
  content: ["./**/*.php"],
  theme: {
    extend: {
      colors: {
        // colors
        primary: "#149E85",
        primary400: "#7DFFE7",
        primary200: "#C8FFF5",
        secondary: "#FEA36B",
        secondary400: "#FFC39E",
        secondary200: "#FFF2DB",
        white: "#fff",
        gray2: "#F3F3F3",
        gray3: "#E2E4E9",
        gray4: "#CCCCCC",
        gray5: "#8D8D8D",
        gray6: "#64748B",
        gray7: "#555556",
        gray8: "#272726",
        darkBlue: "#1275B1",
        navy: "#3B7793",
        success: "#36A54F",
        successlt: "#A8E1B4",
        green: "#0FC874",
        greenlt: "#6CDE00",
        warning: "#FCB400",
        yellow: "#F5CC00",
        danger: "#E55B5B",
        redish: "#FF6E6E",
        cyan: "#06B6D4",
        violet: "#6183FF",
        violetmid: "#6B94FB",
        extraviolet: "#7656F0",
        violetdark: "#932EFA",
        pink: "#EF5DA8",
        pinklt: "#FFC1DF",
        pinkdark: "#EE4195",
        sky: "#06B6D4",
        skylt: "#ABF1FD",
        skydark: "#4EADE3",

        // backgrounds colors
        bgprimary: "#F2FFFD",
        bgsuccess: "#D8FFE1",
        bgviolet: "#E8EDFF",
        bgmint: "#E7FFD0",
        bgsky: "#DDFAFF",
        bglevendermist: "#ECEEF2",
        bgmistyrose: "#FFE5E5",
        bgcream: "#FFF8EB",
        bgiceblue: "#F6FAFD",
        bgaqua: "#E8FFFB",
        bgsnowgray: "#F5F5F5",
        bgfog: "#F9FAF9",
      },
    },
  },
  plugins: [tailwindcss()],
};
